-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity krnl_mmult_krnl_mmult_Pipeline_readB_readB_inner is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    zext_ln212_1 : IN STD_LOGIC_VECTOR (11 downto 0);
    sext_ln221 : IN STD_LOGIC_VECTOR (57 downto 0);
    bound29 : IN STD_LOGIC_VECTOR (75 downto 0);
    localB_0_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    localB_0_ce0 : OUT STD_LOGIC;
    localB_0_we0 : OUT STD_LOGIC;
    localB_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    localB_1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    localB_1_ce0 : OUT STD_LOGIC;
    localB_1_we0 : OUT STD_LOGIC;
    localB_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    localB_2_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    localB_2_ce0 : OUT STD_LOGIC;
    localB_2_we0 : OUT STD_LOGIC;
    localB_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    localB_3_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    localB_3_ce0 : OUT STD_LOGIC;
    localB_3_we0 : OUT STD_LOGIC;
    localB_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    localB_4_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    localB_4_ce0 : OUT STD_LOGIC;
    localB_4_we0 : OUT STD_LOGIC;
    localB_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    localB_5_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    localB_5_ce0 : OUT STD_LOGIC;
    localB_5_we0 : OUT STD_LOGIC;
    localB_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    localB_6_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    localB_6_ce0 : OUT STD_LOGIC;
    localB_6_we0 : OUT STD_LOGIC;
    localB_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    localB_7_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    localB_7_ce0 : OUT STD_LOGIC;
    localB_7_we0 : OUT STD_LOGIC;
    localB_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of krnl_mmult_krnl_mmult_Pipeline_readB_readB_inner is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv480_lc_1 : STD_LOGIC_VECTOR (479 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv76_0 : STD_LOGIC_VECTOR (75 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv76_1 : STD_LOGIC_VECTOR (75 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv13_1000 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal icmp_ln221_reg_459 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln224_reg_474 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op35_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln221_fu_283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln221_reg_459_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_fu_297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_reg_463 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln223_reg_463_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln221_fu_303_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln221_reg_469 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln221_reg_469_pp0_iter2_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln224_fu_315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln224_reg_474_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_addr_read_reg_478 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal ap_phi_mux_empty_phi_fu_246_p4 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_reg_pp0_iter3_empty_reg_243 : STD_LOGIC_VECTOR (511 downto 0);
    signal shiftreg_cast_fu_373_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal k_1_cast77_fu_378_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shiftreg_fu_100 : STD_LOGIC_VECTOR (479 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal k_1_fu_104 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln223_fu_321_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal j_fu_108 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln221_2_fu_362_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln212_1_cast_fu_256_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten32_fu_112 : STD_LOGIC_VECTOR (75 downto 0);
    signal add_ln221_fu_288_p2 : STD_LOGIC_VECTOR (75 downto 0);
    signal trunc_ln221_fu_369_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln224_fu_389_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_44_fu_311_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln221_1_fu_356_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln221_1_fu_349_p3 : STD_LOGIC_VECTOR (479 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component krnl_mmult_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component krnl_mmult_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten32_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten32_fu_112 <= ap_const_lv76_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln221_fu_283_p2 = ap_const_lv1_0))) then 
                    indvar_flatten32_fu_112 <= add_ln221_fu_288_p2;
                end if;
            end if; 
        end if;
    end process;

    j_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    j_fu_108 <= zext_ln212_1_cast_fu_256_p1;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    j_fu_108 <= select_ln221_2_fu_362_p3;
                end if;
            end if; 
        end if;
    end process;

    k_1_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    k_1_fu_104 <= ap_const_lv13_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln221_fu_283_p2 = ap_const_lv1_0))) then 
                    k_1_fu_104 <= add_ln223_fu_321_p2;
                end if;
            end if; 
        end if;
    end process;

    shiftreg_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    shiftreg_fu_100 <= ap_const_lv480_lc_1;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    shiftreg_fu_100 <= ap_phi_mux_empty_phi_fu_246_p4(511 downto 32);
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln221_reg_459 <= icmp_ln221_fu_283_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_predicate_op35_read_state3 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                gmem_addr_read_reg_478 <= m_axi_gmem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln221_reg_459_pp0_iter2_reg <= icmp_ln221_reg_459;
                icmp_ln223_reg_463_pp0_iter2_reg <= icmp_ln223_reg_463;
                icmp_ln224_reg_474_pp0_iter2_reg <= icmp_ln224_reg_474;
                select_ln221_reg_469_pp0_iter2_reg <= select_ln221_reg_469;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln221_fu_283_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln223_reg_463 <= icmp_ln223_fu_297_p2;
                icmp_ln224_reg_474 <= icmp_ln224_fu_315_p2;
                select_ln221_reg_469 <= select_ln221_fu_303_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln221_1_fu_356_p2 <= std_logic_vector(unsigned(j_fu_108) + unsigned(ap_const_lv64_1));
    add_ln221_fu_288_p2 <= std_logic_vector(unsigned(indvar_flatten32_fu_112) + unsigned(ap_const_lv76_1));
    add_ln223_fu_321_p2 <= std_logic_vector(unsigned(select_ln221_fu_303_p3) + unsigned(ap_const_lv13_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_RVALID, ap_predicate_op35_read_state3)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_predicate_op35_read_state3 = ap_const_boolean_1) and (m_axi_gmem_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_RVALID, ap_predicate_op35_read_state3)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_predicate_op35_read_state3 = ap_const_boolean_1) and (m_axi_gmem_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter2_assign_proc : process(m_axi_gmem_RVALID, ap_predicate_op35_read_state3)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((ap_predicate_op35_read_state3 = ap_const_boolean_1) and (m_axi_gmem_RVALID = ap_const_logic_0));
    end process;

        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln221_fu_283_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln221_fu_283_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln221_reg_459, ap_block_pp0_stage0_subdone)
    begin
        if (((icmp_ln221_reg_459 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_phi_mux_empty_phi_fu_246_p4_assign_proc : process(icmp_ln221_reg_459_pp0_iter2_reg, icmp_ln224_reg_474_pp0_iter2_reg, gmem_addr_read_reg_478, ap_phi_reg_pp0_iter3_empty_reg_243, shiftreg_cast_fu_373_p1)
    begin
        if ((icmp_ln221_reg_459_pp0_iter2_reg = ap_const_lv1_0)) then
            if ((icmp_ln224_reg_474_pp0_iter2_reg = ap_const_lv1_0)) then 
                ap_phi_mux_empty_phi_fu_246_p4 <= shiftreg_cast_fu_373_p1;
            elsif ((icmp_ln224_reg_474_pp0_iter2_reg = ap_const_lv1_1)) then 
                ap_phi_mux_empty_phi_fu_246_p4 <= gmem_addr_read_reg_478;
            else 
                ap_phi_mux_empty_phi_fu_246_p4 <= ap_phi_reg_pp0_iter3_empty_reg_243;
            end if;
        else 
            ap_phi_mux_empty_phi_fu_246_p4 <= ap_phi_reg_pp0_iter3_empty_reg_243;
        end if; 
    end process;

    ap_phi_reg_pp0_iter3_empty_reg_243 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op35_read_state3_assign_proc : process(icmp_ln221_reg_459, icmp_ln224_reg_474)
    begin
                ap_predicate_op35_read_state3 <= ((icmp_ln224_reg_474 = ap_const_lv1_1) and (icmp_ln221_reg_459 = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    empty_44_fu_311_p1 <= select_ln221_fu_303_p3(4 - 1 downto 0);

    gmem_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_RVALID, ap_predicate_op35_read_state3, ap_block_pp0_stage0)
    begin
        if (((ap_predicate_op35_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem_blk_n_R <= m_axi_gmem_RVALID;
        else 
            gmem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln221_fu_283_p2 <= "1" when (indvar_flatten32_fu_112 = bound29) else "0";
    icmp_ln223_fu_297_p2 <= "1" when (k_1_fu_104 = ap_const_lv13_1000) else "0";
    icmp_ln224_fu_315_p2 <= "1" when (empty_44_fu_311_p1 = ap_const_lv4_0) else "0";
    k_1_cast77_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln221_reg_469_pp0_iter2_reg),64));
    localB_0_address0 <= k_1_cast77_fu_378_p1(12 - 1 downto 0);

    localB_0_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            localB_0_ce0 <= ap_const_logic_1;
        else 
            localB_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localB_0_d0 <= trunc_ln224_fu_389_p1;

    localB_0_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, trunc_ln221_fu_369_p1)
    begin
        if (((trunc_ln221_fu_369_p1 = ap_const_lv3_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            localB_0_we0 <= ap_const_logic_1;
        else 
            localB_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    localB_1_address0 <= k_1_cast77_fu_378_p1(12 - 1 downto 0);

    localB_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            localB_1_ce0 <= ap_const_logic_1;
        else 
            localB_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localB_1_d0 <= trunc_ln224_fu_389_p1;

    localB_1_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, trunc_ln221_fu_369_p1)
    begin
        if (((trunc_ln221_fu_369_p1 = ap_const_lv3_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            localB_1_we0 <= ap_const_logic_1;
        else 
            localB_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    localB_2_address0 <= k_1_cast77_fu_378_p1(12 - 1 downto 0);

    localB_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            localB_2_ce0 <= ap_const_logic_1;
        else 
            localB_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localB_2_d0 <= trunc_ln224_fu_389_p1;

    localB_2_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, trunc_ln221_fu_369_p1)
    begin
        if (((trunc_ln221_fu_369_p1 = ap_const_lv3_2) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            localB_2_we0 <= ap_const_logic_1;
        else 
            localB_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    localB_3_address0 <= k_1_cast77_fu_378_p1(12 - 1 downto 0);

    localB_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            localB_3_ce0 <= ap_const_logic_1;
        else 
            localB_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localB_3_d0 <= trunc_ln224_fu_389_p1;

    localB_3_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, trunc_ln221_fu_369_p1)
    begin
        if (((trunc_ln221_fu_369_p1 = ap_const_lv3_3) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            localB_3_we0 <= ap_const_logic_1;
        else 
            localB_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    localB_4_address0 <= k_1_cast77_fu_378_p1(12 - 1 downto 0);

    localB_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            localB_4_ce0 <= ap_const_logic_1;
        else 
            localB_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localB_4_d0 <= trunc_ln224_fu_389_p1;

    localB_4_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, trunc_ln221_fu_369_p1)
    begin
        if (((trunc_ln221_fu_369_p1 = ap_const_lv3_4) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            localB_4_we0 <= ap_const_logic_1;
        else 
            localB_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    localB_5_address0 <= k_1_cast77_fu_378_p1(12 - 1 downto 0);

    localB_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            localB_5_ce0 <= ap_const_logic_1;
        else 
            localB_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localB_5_d0 <= trunc_ln224_fu_389_p1;

    localB_5_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, trunc_ln221_fu_369_p1)
    begin
        if (((trunc_ln221_fu_369_p1 = ap_const_lv3_5) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            localB_5_we0 <= ap_const_logic_1;
        else 
            localB_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    localB_6_address0 <= k_1_cast77_fu_378_p1(12 - 1 downto 0);

    localB_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            localB_6_ce0 <= ap_const_logic_1;
        else 
            localB_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localB_6_d0 <= trunc_ln224_fu_389_p1;

    localB_6_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, trunc_ln221_fu_369_p1)
    begin
        if (((trunc_ln221_fu_369_p1 = ap_const_lv3_6) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            localB_6_we0 <= ap_const_logic_1;
        else 
            localB_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    localB_7_address0 <= k_1_cast77_fu_378_p1(12 - 1 downto 0);

    localB_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            localB_7_ce0 <= ap_const_logic_1;
        else 
            localB_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    localB_7_d0 <= trunc_ln224_fu_389_p1;

    localB_7_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, trunc_ln221_fu_369_p1)
    begin
        if (((trunc_ln221_fu_369_p1 = ap_const_lv3_7) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            localB_7_we0 <= ap_const_logic_1;
        else 
            localB_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_ARID <= ap_const_lv1_0;
    m_axi_gmem_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_ARVALID <= ap_const_logic_0;
    m_axi_gmem_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_AWID <= ap_const_lv1_0;
    m_axi_gmem_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_AWVALID <= ap_const_logic_0;
    m_axi_gmem_BREADY <= ap_const_logic_0;

    m_axi_gmem_RREADY_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op35_read_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op35_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_WDATA <= ap_const_lv512_lc_1;
    m_axi_gmem_WID <= ap_const_lv1_0;
    m_axi_gmem_WLAST <= ap_const_logic_0;
    m_axi_gmem_WSTRB <= ap_const_lv64_0;
    m_axi_gmem_WUSER <= ap_const_lv1_0;
    m_axi_gmem_WVALID <= ap_const_logic_0;
    select_ln221_1_fu_349_p3 <= 
        ap_const_lv480_lc_1 when (icmp_ln223_reg_463_pp0_iter2_reg(0) = '1') else 
        shiftreg_fu_100;
    select_ln221_2_fu_362_p3 <= 
        add_ln221_1_fu_356_p2 when (icmp_ln223_reg_463_pp0_iter2_reg(0) = '1') else 
        j_fu_108;
    select_ln221_fu_303_p3 <= 
        ap_const_lv13_0 when (icmp_ln223_fu_297_p2(0) = '1') else 
        k_1_fu_104;
    shiftreg_cast_fu_373_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln221_1_fu_349_p3),512));
    trunc_ln221_fu_369_p1 <= select_ln221_2_fu_362_p3(3 - 1 downto 0);
    trunc_ln224_fu_389_p1 <= ap_phi_mux_empty_phi_fu_246_p4(32 - 1 downto 0);
    zext_ln212_1_cast_fu_256_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln212_1),64));
end behav;
